services:
  sistemagestaomanutencaoindustrial:
    image: sistemagestaomanutencaoindustrial
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005,quiet=y
    ports:
      - 5005:5005
      - 5005:5005
